GRANT CONNECT ON DATABASE amazon TO amazon;


GRANT USAGE ON SCHEMA public TO amazon;
GRANT CREATE ON SCHEMA public TO amazon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO amazon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO amazon;

